# Generated by Django 4.1.3 on 2022-12-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Заголовок', models.CharField(max_length=255)),
                ('URL', models.SlugField()),
                ('Текст статьи', models.TextField(max_length=255)),
                ('Фото', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('Время создания', models.DateTimeField(auto_now_add=True)),
                ('Последнее обновление', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
